'use server';

/**
 * @fileOverview Statically defined question bank for interviews.
 *
 * - generateInterviewQuestions - Function to select questions from the bank.
 * - GenerateInterviewQuestionsInput - Input type for the function.
 * - GenerateInterviewQuestionsOutput - Output type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInterviewQuestionsInputSchema = z.object({
  topics: z.array(z.string()).describe('A list of technical topics for the interview.'),
});
export type GenerateInterviewQuestionsInput = z.infer<typeof GenerateInterviewQuestionsInputSchema>;

const GenerateInterviewQuestionsOutputSchema = z.object({
  questions: z.array(z.string()).describe('An array of 15 interview questions.'),
});
export type GenerateInterviewQuestionsOutput = z.infer<typeof GenerateInterviewQuestionsOutputSchema>;


const QUESTION_BANK = {
  react: [
    'What is React and why is it used?',
    'What are components in React?',
    'What is the difference between props and state?',
    'What is JSX?',
    'What are functional and class components?',
    'How does the Virtual DOM work in React?',
    'What is the purpose of keys in a list?',
    'What is a controlled component in React?',
    'How does React handle form inputs?',
    'What are React hooks?',
    'What does the useState hook do?',
    'What is the useEffect hook used for?',
    'What is prop drilling and how can it be avoided?',
    'What are fragments in React?',
    'How do you conditionally render components in React?',
    'What is the purpose of useRef?',
    'How do you handle side effects in React?',
    'What is the Context API and when would you use it?',
    'What are custom hooks and why are they useful?',
    'What is the difference between useMemo and useCallback?',
    'What is reconciliation in React?',
    'What are Higher Order Components (HOCs)?',
    'What is lazy loading in React and how is it implemented?',
    'What is code splitting?',
    'How does React optimize performance during re-renders?',
    'What are pure components?',
    'How does React differ from other frameworks like Angular or Vue?',
    'What is React Router and how does it work?',
    'How do you pass parameters in React Router?',
    'What are the differences between useEffect and componentDidMount?',
    'What is Redux and why is it used with React?',
    'What are actions, reducers, and the store in Redux?',
    'What is the difference between Redux and Context API?',
    'What are middleware in Redux?',
    'What is the useReducer hook?',
    'How do you deploy a React application?',
    'What is Create React App (CRA)?',
    'What is the difference between CRA and Vite?',
    'How can you improve performance in a large React application?',
    'What is tree shaking?',
    'How do you secure a React app?',
    'What are common React anti-patterns to avoid?',
    'How can you handle errors in React components?',
    'What is the purpose of error boundaries?',
    'What is Server-Side Rendering (SSR) in React?',
    'What is hydration in React?',
    'How does React handle accessibility (a11y)?',
    'How can you test a React component?',
    'What is snapshot testing?',
    'What are best practices for structuring a scalable React project?',
  ],
  java: [
    'What is the JVM and its components?',
    'Explain JRE vs JDK.',
    'How does Java achieve platform independence?',
    'What are the four OOP principles?',
    'Difference between `equals()` and `==`.',
    'Explain `HashMap` vs `Hashtable`.',
    'What is method overloading vs overriding?',
    'How does garbage collection work?',
    'What’s the difference between `final`, `finally`, and `finalize`.',
    'Explain Java memory model.',
    'What’s a thread and how do you create one?',
    'Explain synchronized blocks.',
    'How do `wait()` and `notify()` work?',
    'Compare Thread vs Runnable.',
    'What’s an immutable class?',
    'Explain Java 8 streams.',
    'What are functional interfaces?',
    'What is lambda notation?',
    'Explain Optional and why it’s used.',
    'What are default and static methods in interfaces?',
    'Describe Java class loaders.',
    'Explain reflection API.',
    'What’s serialization? How do you customize it?',
    'What is a Singleton and how do you implement thread-safe?',
    'Explain design patterns like Factory, Observer.',
    'What are generics, and why use them?',
    'What’s type erasure?',
    'Explain bounded type parameters.',
    'Difference between `List`, `Set`, and `Map`.',
    'Compare `ArrayList` and `LinkedList`.',
    'Explain `Comparable` vs `Comparator`.',
    'What are checked vs unchecked exceptions?',
    'How do you implement custom exception?',
    'Describe try-with-resources.',
    'Explain Enum types.',
    'How does `String` pool work?',
    'What’s the difference between `StringBuilder` and `StringBuffer`.',
    'How do you convert between primitive and wrapper types?',
    'What’s autoboxing and unboxing?',
    'Explain volatile keyword.',
    'What is concurrency and parallelism in Java?',
    'What are CompletableFutures?',
    'Explain the Fork/Join framework.',
    'What are annotations and how to create custom ones?',
    'How do you implement AOP in Java?',
    'Explain JVM tuning basics.',
    'What is JIT compiler?',
    'Describe memory leaks in Java.',
    'How do you profile a Java application?',
    'What’s a microservice and how would you implement one using Java frameworks?',
  ],
  c: [
    'What are the basic data types in C?',
    'Differences between `malloc()` and `calloc()`.',
    'Explain pointer and how to use it.',
    'What is pointer arithmetic?',
    'How do you pass arguments by reference?',
    'Explain memory layout of a C program.',
    'What is a segmentation fault?',
    'What are the storage classes (`static`, `extern`, etc.)?',
    'How does `const` work with pointers?',
    'What is a memory leak?',
    'How to prevent buffer overflow?',
    'Difference between stack and heap.',
    'Explain `struct` and `union`.',
    'How do bitfields work?',
    'What is the `volatile` keyword?',
    'How does `inline` function work?',
    'Explain function pointers.',
    'How to use callbacks in C?',
    'Difference between arrays and pointers.',
    'Explain C preprocessor directives.',
    'What is `#define` vs `const`.',
    'Explain macros and pitfalls.',
    'What is header guard and why needed?',
    'Explain dynamic memory management.',
    'How to use `realloc()`.',
    'What is the difference between `fopen()` modes?',
    'How do you read/write binary files?',
    'What is `EOF`?',
    'Explain `printf()` formatting specifiers.',
    'How to handle errors in C?',
    'What’s `errno` and how to use it?',
    'Explain `setjmp()`/`longjmp()`.',
    'What are undefined and unspecified behaviors?',
    'Explain `struct` padding and alignment.',
    'What’s the `restrict` keyword?',
    'How do you create a linked list?',
    'How to implement stack using arrays/pointers?',
    'Write a function to reverse a string in-place.',
    'Write code to swap two variables without a temp.',
    'What are memory-mapped files?',
    'Explain makefiles and their use.',
    'How to link multiple C files together.',
    'What is static vs dynamic linking.',
    'How to debug with `gdb`.',
    'What is Valgrind and how to detect leaks.',
    'Explain signal handling.',
    'What is `fork()`?',
    'What is `exec()` family?',
    'How to use `pipe()` for IPC?',
    'Explain process vs thread in C context.',
  ],
  'c++': [
    'What are the major differences between C and C++?',
    'Explain classes, objects, and access specifiers.',
    'What is RAII?',
    'What are constructors/destructors?',
    'Explain copy constructor and assignment operator.',
    'What is move semantics?',
    'Explain smart pointers: `unique_ptr`, `shared_ptr`.',
    'What is polymorphism?',
    'Explain virtual functions and vtable.',
    'What are templates?',
    'What is template specialization?',
    'What is STL?',
    'How do `vector`, `list`, `map` differ?',
    'Explain iterators.',
    'What are functors?',
    'Explain lambda expressions.',
    'What is Exception handling in C++?',
    'How does `noexcept` work?',
    'What is `constexpr`?',
    'Difference between `new/delete` and `malloc/free`.',
    'Explain operator overloading.',
    'What is multiple inheritance?',
    'Explain virtual inheritance.',
    'What is an abstract class?',
    'What are namespaces?',
    'What is inline function?',
    'How does linking work in C++?',
    'What is ODR (One Definition Rule)?',
    'Explain move constructor.',
    'What is SFINAE?',
    'Explain C++11 features.',
    'What are the differences in C++14/17/20?',
    'What is `std::optional`?',
    'What is `std::variant`?',
    'What is CRTP?',
    'Explain PImpl idiom.',
    'How do you do thread synchronization in C++?',
    'Explain `std::thread`.',
    'What is `std::async`?',
    'How does memory model work in C++?',
    'What is UB (undefined behavior)?',
    'Explain `static_cast`, `dynamic_cast`, etc.',
    'What is RTTI?',
    'How to use debug vs release builds?',
    'What are design patterns in C++?',
    'How would you manage resource leaks?',
    'What are allocators?',
    'Explain move-only types.',
    'What is `std::span`?',
    'Explain modules in C++20.',
  ],
  javascript: [
    'What are the different data types in JS?',
    'Explain `let`, `const`, and `var`.',
    'What is hoisting?',
    'What is closure and how is it used?',
    'Difference between `==` and `===`.',
    'What is event bubbling and capturing?',
    'What is the DOM?',
    'Explain arrow functions.',
    'What is a callback function?',
    'What are promises?',
    'Explain async/await.',
    'What is the event loop in JavaScript?',
    'What is the call stack?',
    'Explain lexical scope.',
    'What are template literals?',
    'Difference between `null` and `undefined`.',
    'What is NaN?',
    'What is a pure function?',
    'What is IIFE?',
    'Explain currying.',
    'What are higher-order functions?',
    'How do you debounce a function?',
    'What is `this` in JS?',
    'Difference between regular and arrow functions (`this` binding).',
    'What is `bind()`, `call()`, and `apply()`?',
    'Explain prototypal inheritance.',
    'What is the prototype chain?',
    'What is `Object.create()`?',
    'How does `map`, `filter`, `reduce` work?',
    'What are spread and rest operators?',
    'How to clone an object?',
    'What are symbols?',
    'What is `typeof` and `instanceof`?',
    'How to handle errors in async functions?',
    'What is a module in JavaScript?',
    'What are ES6 classes?',
    'Difference between synchronous and asynchronous code.',
    'What are generators?',
    'What is a WeakMap and WeakSet?',
    'Explain event delegation.',
    'What is CORS?',
    'Explain the fetch API.',
    'What are service workers?',
    'How does localStorage differ from sessionStorage?',
    'What is the purpose of `use strict`?',
    'Explain destructuring.',
    'What is a JavaScript engine?',
    'What is tail call optimization?',
    'Difference between deep and shallow copy.',
    'What is the Temporal API?',
  ],
  php: [
    'What is PHP and where is it used?',
    'Difference between `echo`, `print`, and `print_r`.',
    'How does PHP handle variables?',
    'What are variable scopes?',
    'Difference between `include`, `require`, `include_once`, `require_once`.',
    'What is a session and how is it handled?',
    'What are cookies and how do they differ from sessions?',
    'How do you connect to a MySQL database in PHP?',
    'What is PDO?',
    'How do you prevent SQL Injection in PHP?',
    'What is XSS and how to prevent it in PHP?',
    'How to upload files using PHP?',
    'What is the difference between `GET` and `POST`?',
    'What is an associative array?',
    'How do you handle errors in PHP?',
    'What is `isset()` vs `empty()`?',
    'How to create and use functions?',
    'What is a constructor in PHP?',
    'What is inheritance?',
    'Explain interfaces and traits in PHP.',
    'What are magic methods like `__get()` and `__set()`?',
    'What is `namespace` in PHP?',
    'What is Composer?',
    'What is autoloading?',
    'How do you use PHP for REST APIs?',
    'Difference between `==` and `===` in PHP.',
    'What are anonymous functions?',
    'What is output buffering?',
    'What is `die()` vs `exit()`?',
    'What are access modifiers in PHP?',
    'What is the `final` keyword?',
    'Explain file handling in PHP.',
    'How do sessions persist in PHP?',
    'How to encrypt passwords in PHP?',
    'How to create a login system in PHP?',
    'What is `spl_autoload_register()`?',
    'Explain regular expressions in PHP.',
    'What is an exception in PHP?',
    'How does `try-catch-finally` work?',
    'Difference between static and dynamic websites.',
    'What are global variables and how to use them?',
    'What are the superglobals (`$_GET`, `$_POST`, `$_SESSION`, etc.)?',
    'How to validate form data in PHP?',
    'What is `json_encode()` and `json_decode()`?',
    'How do you set HTTP headers in PHP?',
    'What is output escaping?',
    'How to handle file downloads in PHP?',
    'What are PHP frameworks?',
    'What is Laravel, briefly?',
    'How to optimize PHP performance?',
  ],
  kotlin: [
    'What is Kotlin and how does it differ from Java?',
    'What is a data class?',
    'Explain `val` vs `var`.',
    'What is a null-safe operator in Kotlin?',
    'What is the Elvis operator (`?:`)?',
    'How does Kotlin handle null safety?',
    'What are extension functions?',
    'What is a higher-order function?',
    'Explain lambda expressions.',
    'What is a sealed class?',
    'What is the difference between `==` and `===`?',
    'What is a smart cast?',
    'What are default and named arguments?',
    'What is `lateinit`?',
    'What is `object` keyword?',
    'Explain `companion object`.',
    'What is `init` block?',
    'What are infix functions?',
    'How to create a singleton in Kotlin?',
    'What is inline function?',
    'What are reified types?',
    'What is a coroutine?',
    'What is `suspend` function?',
    'How does Kotlin handle concurrency?',
    'What is the difference between `launch` and `async`?',
    'What are `Channel` and `Flow` in Kotlin?',
    'How does exception handling work?',
    'What are collections in Kotlin?',
    'Difference between `List`, `MutableList`, `ArrayList`.',
    'What is a range in Kotlin?',
    'How do you use destructuring declarations?',
    'What are type aliases?',
    'What is destructuring in Kotlin?',
    'How is Kotlin interoperable with Java?',
    'What is a backing property?',
    'What is a delegation pattern?',
    'What are annotations in Kotlin?',
    'What are visibility modifiers?',
    'What are generics in Kotlin?',
    'What is the use of `Nothing` type?',
    'What is `withContext`?',
    'Difference between `map`, `flatMap`, `filter`.',
    'How does Kotlin handle functional programming?',
    'What is a tail-recursive function?',
    'What is `apply`, `let`, `also`, `run`, `with`?',
    'What is a scope function?',
    'How do you define an interface in Kotlin?',
    'What is `enum` and `sealed` class difference?',
    'What is a ViewModel in Android using Kotlin?',
    'What are common pitfalls in Kotlin?',
  ],
  html: [
    'What is HTML?',
    'What’s the structure of a basic HTML page?',
    'What are semantic HTML elements?',
    'Difference between `<div>` and `<span>`?',
    'What does the `<meta>` tag do?',
    'What are HTML5 new features?',
    'What is the `<header>` and `<footer>` tag?',
    'What is the `<section>` tag used for?',
    'What are global attributes?',
    'What is the `alt` attribute for `<img>`?',
    'Difference between `id` and `class`.',
    'How does the `<form>` element work?',
    'What are `input` types in HTML5?',
    'What is `action` and `method` in forms?',
    'Difference between `GET` and `POST`.',
    'What is HTML entity?',
    'What is the purpose of `doctype`?',
    'What is a block-level vs inline element?',
    'What are void elements in HTML?',
    'What is the `<canvas>` tag?',
    'What is the `<video>` and `<audio>` tag?',
    'What is a favicon and how is it added?',
    'How to add an external JavaScript file?',
    'How to link CSS to HTML?',
    'What is `<iframe>`?',
    'What is the `<nav>` element?',
    'What are ARIA roles in HTML?',
    'What is the `<progress>` tag?',
    'What is the `<dialog>` element?',
    'What is the difference between `<b>` and `<strong>`?',
    'What is the difference between `<i>` and `<em>`?',
    'How to make an image responsive in HTML?',
    'What is the `<picture>` tag?',
    'How do you create tables in HTML?',
    'What are table-related tags?',
    'What is accessibility in HTML?',
    'What is a data-\* attribute?',
    'What is the difference between `<ol>`, `<ul>`, and `<dl>`?',
    'What is the `<mark>` tag?',
    'What is the purpose of `<template>`?',
    'What is a custom data attribute?',
    'How does the `<details>` and `<summary>` tag work?',
    'What is cross-origin in HTML context?',
    'What are deprecated tags?',
    'How to create a hyperlink?',
    'What is the target attribute in `<a>` tag?',
    'What is inline SVG in HTML?',
    'How to disable autocomplete in forms?',
    'What is responsive design?',
    'What is viewport meta tag?',
  ],
  css: [
    'What is CSS?',
    'What are different types of CSS?',
    'What is specificity in CSS?',
    'How does the cascade work in CSS?',
    'What is the difference between `em`, `rem`, `%`, `px`?',
    'What is `z-index`?',
    'How do media queries work?',
    'What is the box model?',
    'What is `position: relative`, `absolute`, `fixed`, `sticky`?',
    'How does flexbox work?',
    'What is the difference between `justify-content` and `align-items`?',
    'How do CSS Grid and Flexbox differ?',
    'What is a pseudo-class?',
    'What is a pseudo-element?',
    'What is the difference between `:nth-child()` and `:nth-of-type()`?',
    'What are transitions in CSS?',
    'What are keyframes and how do animations work?',
    'What is `calc()` in CSS?',
    'What is `clamp()` in CSS?',
    'How does `min()` and `max()` work?',
    'How to make responsive designs in CSS?',
    'What is the difference between `visibility: hidden` and `display: none`?',
    'What is specificity hierarchy?',
    'How to center a div in CSS?',
    'What is a CSS variable?',
    'What are custom properties?',
    'What is `inherit`, `initial`, `unset`?',
    'What is `!important` and when to use it?',
    'What is a shadow DOM?',
    'How does `overflow` work?',
    'What is stacking context?',
    'How do `vh`, `vw`, `vmin`, `vmax` work?',
    'What is the difference between inline, block, and inline-block?',
    'What is `object-fit` and `object-position`?',
    'How to style an SVG with CSS?',
    'What is the `backface-visibility` property?',
    'How to use web fonts in CSS?',
    'What is `@font-face`?',
    'What is a reset or normalize CSS?',
    'What are grid template areas?',
    'What is logical property (e.g., `margin-inline`)?',
    'What are combinators in CSS?',
    'How do you use `nth-child(even)` and `odd`?',
    'What are descendant selectors?',
    'How do you hide elements visually but keep them accessible?',
    'What is the difference between hover and focus?',
    'What are media features (`prefers-color-scheme`, etc.)?',
    'How to make dark mode with CSS only?',
    'What is the difference between a reset and a normalize stylesheet?',
    'What are layered backgrounds?',
  ],
  go: [
    'What is Go and where is it used?',
    'How does Go manage memory?',
    'What is the difference between `var`, `:=`, and `const`?',
    'What are slices in Go?',
    'What are maps and how do they differ from slices?',
    'What is a struct?',
    'What is an interface in Go?',
    'What is the empty interface (`interface{}`)?',
    'What is a pointer in Go?',
    'How does Go handle concurrency?',
    'What are goroutines?',
    'What are channels?',
    'Buffered vs unbuffered channels?',
    'What is a select statement?',
    'How do you handle race conditions?',
    'What is a defer statement?',
    'How does panic and recover work?',
    'What is the Go garbage collector?',
    'What is a package in Go?',
    'How does Go handle error handling?',
    'How do you create and use custom errors?',
    'What is a closure in Go?',
    'What are Go modules?',
    'What is the Go workspace (`go.work`)?',
    'What is the use of `init()` function?',
    'What is shadowing in Go?',
    'How to implement a singleton in Go?',
    'How does type embedding work in structs?',
    'How does Go manage dependencies?',
    'What is the zero value in Go?',
    'What is method receiver and pointer receiver?',
    'How do you write tests in Go?',
    'What is a benchmark test?',
    'How to run unit tests using `go test`?',
    'What is reflection in Go?',
    'What is JSON marshalling and unmarshalling?',
    'How to perform HTTP requests in Go?',
    'What are middleware functions?',
    'What are context and cancellation in Go?',
    'What is sync.WaitGroup?',
    'What is a mutex and when to use it?',
    'Explain `sync.Once`.',
    'How to detect memory leaks?',
    'What is the Go playground?',
    'How does Go differ from Java/Python/C++?',
    'What is a build tag?',
    'What is `go fmt`?',
    'What are iota and enumerations?',
    'What is interface assertion?',
    'What is Go’s philosophy: simplicity and minimalism?',
  ],
  python: [
    'What are Python\'s key features?',
    'What are Python data types?',
    'What is the difference between list, tuple, and set?',
    'What is a dictionary in Python?',
    'What is list comprehension?',
    'What are *args and **kwargs?',
    'What is the difference between `is` and `==`?',
    'What is a lambda function?',
    'What is a generator?',
    'What is a decorator?',
    'What is a context manager?',
    'What does the `with` statement do?',
    'What is `None` in Python?',
    'What is duck typing?',
    'What is a module and a package?',
    'What is the difference between `import` and `from import`?',
    'What is pip?',
    'What are virtual environments?',
    'What is `__init__.py`?',
    'What is Python’s GIL?',
    'What is the difference between `deepcopy` and `copy`?',
    'What is the difference between mutable and immutable types?',
    'What are Python’s scope rules (LEGB)?',
    'What are Python exceptions and how to handle them?',
    'What is a custom exception?',
    'What is the difference between `finally`, `else`, and `try`?',
    'What is monkey patching?',
    'What is the difference between `@staticmethod` and `@classmethod`?',
    'What is `super()`?',
    'What is polymorphism in Python?',
    'What is the `self` keyword?',
    'How does Python implement inheritance?',
    'What are metaclasses?',
    'What is `__str__` and `__repr__`?',
    'What is the difference between `range()` and `xrange()`?',
    'What is a memory view object?',
    'What are f-strings in Python 3.6+?',
    'What are iterators and iterables?',
    'What is the difference between `==` and `is`?',
    'What are asyncio and `await`/`async`?',
    'What are Python data classes?',
    'What is `__slots__`?',
    'What are modules like NumPy, Pandas, etc. used for?',
    'What is the `__main__` convention?',
    'What is serialization with `pickle` or `json`?',
    'What is the use of `enumerate()`?',
    'What is the purpose of `zip()`?',
    'What are common Python design patterns?',
    'How is Python memory managed?',
    'What are some Python interview coding challenges?',
  ],
  typescript: [
    'What is TypeScript and how is it different from JS?',
    'What are TypeScript’s primitive types?',
    'What is type inference?',
    'What are interfaces in TypeScript?',
    'What is the difference between `interface` and `type`?',
    'What are optional properties?',
    'What is a union type?',
    'What is an intersection type?',
    'What is a tuple in TypeScript?',
    'What are enums?',
    'What are type assertions?',
    'What is `any`, `unknown`, and `never`?',
    'What are generics in TypeScript?',
    'How to use default generics?',
    'What is type narrowing?',
    'What are mapped types?',
    'What is conditional typing?',
    'What is a utility type (`Partial`, `Pick`, `Omit`, etc.)?',
    'What is the difference between `void` and `never`?',
    'How does TypeScript support OOP?',
    'What are access modifiers (`public`, `private`, `protected`)?',
    'What is a decorator in TypeScript?',
    'How to define a function type?',
    'How do you handle modules in TypeScript?',
    'What is a namespace?',
    'How do you compile TypeScript?',
    'How do you integrate TypeScript with Webpack?',
    'What is the `tsconfig.json` file?',
    'How to enable strict typing?',
    'What is `readonly` in TypeScript?',
    'How to create custom types?',
    'How to handle DOM elements in TS?',
    'What is a discriminated union?',
    'What is declaration merging?',
    'What is a literal type?',
    'What is structural typing?',
    'How do you type a React component with TypeScript?',
    'What are JSX and TSX files?',
    'How do you handle third-party libraries without types?',
    'How do you install type declarations?',
    'How to write and export TypeScript modules?',
    'What are triple-slash directives?',
    'What is the `keyof` operator?',
    'What is the `in` keyword in mapped types?',
    'What are index signatures?',
    'What is a function overload in TypeScript?',
    'How does `as const` work?',
    'What are template literal types?',
    'What is `this` in TypeScript class methods?',
    'How to migrate JavaScript project to TypeScript?',
  ],
  rust: [
    'What is Rust and why is it considered safe?',
    'What is ownership in Rust?',
    'What are borrowing and references?',
    'What is the difference between `&T` and `&mut T`?',
    'What is the concept of lifetimes in Rust?',
    'What is the `Copy` vs `Clone` trait?',
    'What are enums in Rust?',
    'What is a match expression?',
    'What is pattern matching?',
    'What are traits in Rust?',
    'What is trait bound syntax (`T: Trait`)?',
    'What is a generic function?',
    'What are closures in Rust?',
    'What is the difference between `Fn`, `FnMut`, and `FnOnce`?',
    'What is `Option<T>` and how is it used?',
    'What is `Result<T, E>` and how to handle errors?',
    'What is `unwrap()`, `expect()`, and why should they be used cautiously?',
    'What is the `?` operator?',
    'What is `match` vs `if let` vs `while let`?',
    'How do iterators work in Rust?',
    'What are `map`, `filter`, and `fold` on iterators?',
    'What is a macro in Rust (`macro_rules!`)',
    'What is the difference between `String` and `&str`?',
    'How does memory allocation work in Rust?',
    'What are crates and how does Cargo work?',
    'What is the `lib.rs` and `main.rs` distinction?',
    'What is the `pub` keyword?',
    'How to organize modules in Rust?',
    'What is a smart pointer (`Box`, `Rc`, `RefCell`)?',
    'Difference between `Rc` and `Arc`.',
    'What is interior mutability?',
    'What are unsafe blocks in Rust?',
    'What is FFI in Rust?',
    'How does concurrency work in Rust?',
    'What are threads and `std::thread` module?',
    'What are channels for communication?',
    'What is async/await in Rust?',
    'What is the `tokio` runtime?',
    'How do you write tests in Rust?',
    'How does `#[derive]` work?',
    'What are attributes in Rust?',
    'How to write documentation with `cargo doc`?',
    'What is a procedural macro?',
    'What is Serde and how to use it for JSON serialization?',
    'What is a lifetime elision?',
    'What is the `static` lifetime?',
    'What is zero-cost abstraction?',
    'What are iterator adapters?',
    'How does Rust prevent data races?',
    'What are key advantages of using Rust over C/C++?',
  ],
  swift: [
    'What is Swift and why is it used?',
    'Difference between `let` and `var`.',
    'What are optionals in Swift?',
    'How does optional binding work (`if let`, `guard let`)?',
    'What are value types vs reference types?',
    'What is a struct in Swift?',
    'What is a class in Swift?',
    'What is an enum in Swift?',
    'What are tuples?',
    'What is a closure in Swift?',
    'What are trailing closures?',
    'What is ARC (Automatic Reference Counting)?',
    'What is a strong vs weak reference?',
    'What are lazy properties?',
    'What are computed properties?',
    'What is a property observer?',
    'What are access control levels (`private`, `fileprivate`, `internal`, etc.)?',
    'What is protocol in Swift?',
    'What is protocol-oriented programming?',
    'What is an extension in Swift?',
    'What are generics in Swift?',
    'What is a delegate?',
    'What are higher-order functions (`map`, `reduce`, `filter`)?',
    'What is a guard statement?',
    'What is the difference between `throw`, `try`, `catch`?',
    'What is error propagation?',
    'What are do-try-catch blocks?',
    'What is `inout` parameter?',
    'What are escaping closures?',
    'What is the difference between synchronous and asynchronous code?',
    'What is Combine framework?',
    'What is `async`/`await` in Swift?',
    'What is SwiftUI?',
    'How does SwiftUI differ from UIKit?',
    'What is a ViewModifier?',
    'What are observed objects (`@State`, `@Binding`, `@ObservedObject`, etc.)?',
    'What is a SceneDelegate and AppDelegate?',
    'What are app life cycle phases in SwiftUI?',
    'What is a Result type?',
    'What are key-value observing (KVO) and key-paths?',
    'What are function types?',
    'What is an initializer?',
    'What are convenience initializers?',
    'What is deinitialization?',
    'What is the use of `Self` in Swift?',
    'What is typecasting in Swift?',
    'What is a singleton and how do you create it in Swift?',
    'What is Codable protocol?',
    'What is `@available` attribute?',
    'How is Swift memory safe?',
  ],
  kubernetes: [
    'What is Kubernetes?',
    'What is the difference between Docker and Kubernetes?',
    'What is a Pod in Kubernetes?',
    'What is a ReplicaSet?',
    'What is a Deployment?',
    'What is a StatefulSet?',
    'What is a DaemonSet?',
    'What is a Job and CronJob?',
    'What is a Service in Kubernetes?',
    'Difference between ClusterIP, NodePort, and LoadBalancer?',
    'What is an Ingress?',
    'What is a Namespace?',
    'What are labels and selectors?',
    'What are annotations?',
    'What is a ConfigMap?',
    'What is a Secret in Kubernetes?',
    'What is a Volume?',
    'What are PersistentVolumes and PersistentVolumeClaims?',
    'What is a StorageClass?',
    'What is the kubelet?',
    'What is etcd in Kubernetes?',
    'What is the role of the scheduler?',
    'What is the API server?',
    'What is a controller manager?',
    'What are taints and tolerations?',
    'What are node affinity and pod affinity?',
    'What is a Helm chart?',
    'What is Helm and how is it used?',
    'What is kubectl and how do you use it?',
    'How do you scale deployments in Kubernetes?',
    'How do you perform rolling updates?',
    'What is a liveness probe?',
    'What is a readiness probe?',
    'How do you manage resource limits in Kubernetes?',
    'What is a horizontal pod autoscaler (HPA)?',
    'What is a custom resource definition (CRD)?',
    'What is a service mesh (e.g., Istio)?',
    'What is kube-proxy?',
    'What is a sidecar container?',
    'How does RBAC work in Kubernetes?',
    'What is a Kubernetes context?',
    'How do you access the Kubernetes dashboard?',
    'What is port forwarding?',
    'How do you troubleshoot a failing pod?',
    'What is a `kubectl describe` vs `kubectl get`?',
    'What is a manifest file?',
    'What is the use of `kubectl logs`?',
    'What is kubeadm?',
    'What is the difference between Minikube and Kind?',
    'How do you backup and restore a Kubernetes cluster?',
  ]
};

export async function generateInterviewQuestions(input: GenerateInterviewQuestionsInput): Promise<GenerateInterviewQuestionsOutput> {
  return generateInterviewQuestionsFlow(input);
}

const generateInterviewQuestionsFlow = ai.defineFlow(
  {
    name: 'generateInterviewQuestionsFlow',
    inputSchema: GenerateInterviewQuestionsInputSchema,
    outputSchema: GenerateInterviewQuestionsOutputSchema,
  },
  async ({ topics }) => {
    let questionPool: string[] = [];

    if (topics.length > 0) {
      topics.forEach(topic => {
        const questionsForTopic = QUESTION_BANK[topic as keyof typeof QUESTION_BANK];
        if (questionsForTopic) {
          questionPool.push(...questionsForTopic);
        }
      });
    }

    // Use a Set to remove duplicate questions if a user selects topics with overlapping questions
    const uniqueQuestions = Array.from(new Set(questionPool));

    // Handle case where no questions were found for selected topics
    if (uniqueQuestions.length === 0) {
      return { questions: ["Tell me about a challenging technical problem you solved recently.", "Describe your experience with version control systems like Git.", "How do you approach learning a new technology?"] };
    }

    // Shuffle the pool to ensure randomness
    const shuffledQuestions = uniqueQuestions.sort(() => 0.5 - Math.random());

    // Select up to 15 questions
    const selectedQuestions = shuffledQuestions.slice(0, 15);

    return { questions: selectedQuestions };
  }
);
